{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "nfs-subdir-external-provisioner.labels" . | nindent 4 }}
  name: run-{{ template "nfs-subdir-external-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nfs-subdir-external-provisioner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "nfs-subdir-external-provisioner.fullname" . }}-runner
  apiGroup: rbac.authorization.k8s.io
{{- end }}
